# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aman/Projects/Steiner

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aman/Projects/Steiner

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aman/Projects/Steiner/CMakeFiles /home/aman/Projects/Steiner/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aman/Projects/Steiner/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named steiner

# Build rule for target.
steiner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 steiner
.PHONY : steiner

# fast build rule for target.
steiner/fast:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/build
.PHONY : steiner/fast

GEOM/GPMinit.o: GEOM/GPMinit.cpp.o
.PHONY : GEOM/GPMinit.o

# target to build an object file
GEOM/GPMinit.cpp.o:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/GEOM/GPMinit.cpp.o
.PHONY : GEOM/GPMinit.cpp.o

GEOM/GPMinit.i: GEOM/GPMinit.cpp.i
.PHONY : GEOM/GPMinit.i

# target to preprocess a source file
GEOM/GPMinit.cpp.i:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/GEOM/GPMinit.cpp.i
.PHONY : GEOM/GPMinit.cpp.i

GEOM/GPMinit.s: GEOM/GPMinit.cpp.s
.PHONY : GEOM/GPMinit.s

# target to generate assembly for a file
GEOM/GPMinit.cpp.s:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/GEOM/GPMinit.cpp.s
.PHONY : GEOM/GPMinit.cpp.s

GEOM/GPMinterface.o: GEOM/GPMinterface.cpp.o
.PHONY : GEOM/GPMinterface.o

# target to build an object file
GEOM/GPMinterface.cpp.o:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/GEOM/GPMinterface.cpp.o
.PHONY : GEOM/GPMinterface.cpp.o

GEOM/GPMinterface.i: GEOM/GPMinterface.cpp.i
.PHONY : GEOM/GPMinterface.i

# target to preprocess a source file
GEOM/GPMinterface.cpp.i:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/GEOM/GPMinterface.cpp.i
.PHONY : GEOM/GPMinterface.cpp.i

GEOM/GPMinterface.s: GEOM/GPMinterface.cpp.s
.PHONY : GEOM/GPMinterface.s

# target to generate assembly for a file
GEOM/GPMinterface.cpp.s:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/GEOM/GPMinterface.cpp.s
.PHONY : GEOM/GPMinterface.cpp.s

GEOM/GPMkdtree.o: GEOM/GPMkdtree.cpp.o
.PHONY : GEOM/GPMkdtree.o

# target to build an object file
GEOM/GPMkdtree.cpp.o:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/GEOM/GPMkdtree.cpp.o
.PHONY : GEOM/GPMkdtree.cpp.o

GEOM/GPMkdtree.i: GEOM/GPMkdtree.cpp.i
.PHONY : GEOM/GPMkdtree.i

# target to preprocess a source file
GEOM/GPMkdtree.cpp.i:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/GEOM/GPMkdtree.cpp.i
.PHONY : GEOM/GPMkdtree.cpp.i

GEOM/GPMkdtree.s: GEOM/GPMkdtree.cpp.s
.PHONY : GEOM/GPMkdtree.s

# target to generate assembly for a file
GEOM/GPMkdtree.cpp.s:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/GEOM/GPMkdtree.cpp.s
.PHONY : GEOM/GPMkdtree.cpp.s

GEOM/GPMmain.o: GEOM/GPMmain.cpp.o
.PHONY : GEOM/GPMmain.o

# target to build an object file
GEOM/GPMmain.cpp.o:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/GEOM/GPMmain.cpp.o
.PHONY : GEOM/GPMmain.cpp.o

GEOM/GPMmain.i: GEOM/GPMmain.cpp.i
.PHONY : GEOM/GPMmain.i

# target to preprocess a source file
GEOM/GPMmain.cpp.i:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/GEOM/GPMmain.cpp.i
.PHONY : GEOM/GPMmain.cpp.i

GEOM/GPMmain.s: GEOM/GPMmain.cpp.s
.PHONY : GEOM/GPMmain.s

# target to generate assembly for a file
GEOM/GPMmain.cpp.s:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/GEOM/GPMmain.cpp.s
.PHONY : GEOM/GPMmain.cpp.s

MinCost/MinCost.o: MinCost/MinCost.cpp.o
.PHONY : MinCost/MinCost.o

# target to build an object file
MinCost/MinCost.cpp.o:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/MinCost/MinCost.cpp.o
.PHONY : MinCost/MinCost.cpp.o

MinCost/MinCost.i: MinCost/MinCost.cpp.i
.PHONY : MinCost/MinCost.i

# target to preprocess a source file
MinCost/MinCost.cpp.i:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/MinCost/MinCost.cpp.i
.PHONY : MinCost/MinCost.cpp.i

MinCost/MinCost.s: MinCost/MinCost.cpp.s
.PHONY : MinCost/MinCost.s

# target to generate assembly for a file
MinCost/MinCost.cpp.s:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/MinCost/MinCost.cpp.s
.PHONY : MinCost/MinCost.cpp.s

PMduals.o: PMduals.cpp.o
.PHONY : PMduals.o

# target to build an object file
PMduals.cpp.o:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/PMduals.cpp.o
.PHONY : PMduals.cpp.o

PMduals.i: PMduals.cpp.i
.PHONY : PMduals.i

# target to preprocess a source file
PMduals.cpp.i:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/PMduals.cpp.i
.PHONY : PMduals.cpp.i

PMduals.s: PMduals.cpp.s
.PHONY : PMduals.s

# target to generate assembly for a file
PMduals.cpp.s:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/PMduals.cpp.s
.PHONY : PMduals.cpp.s

PMexpand.o: PMexpand.cpp.o
.PHONY : PMexpand.o

# target to build an object file
PMexpand.cpp.o:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/PMexpand.cpp.o
.PHONY : PMexpand.cpp.o

PMexpand.i: PMexpand.cpp.i
.PHONY : PMexpand.i

# target to preprocess a source file
PMexpand.cpp.i:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/PMexpand.cpp.i
.PHONY : PMexpand.cpp.i

PMexpand.s: PMexpand.cpp.s
.PHONY : PMexpand.s

# target to generate assembly for a file
PMexpand.cpp.s:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/PMexpand.cpp.s
.PHONY : PMexpand.cpp.s

PMinit.o: PMinit.cpp.o
.PHONY : PMinit.o

# target to build an object file
PMinit.cpp.o:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/PMinit.cpp.o
.PHONY : PMinit.cpp.o

PMinit.i: PMinit.cpp.i
.PHONY : PMinit.i

# target to preprocess a source file
PMinit.cpp.i:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/PMinit.cpp.i
.PHONY : PMinit.cpp.i

PMinit.s: PMinit.cpp.s
.PHONY : PMinit.s

# target to generate assembly for a file
PMinit.cpp.s:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/PMinit.cpp.s
.PHONY : PMinit.cpp.s

PMinterface.o: PMinterface.cpp.o
.PHONY : PMinterface.o

# target to build an object file
PMinterface.cpp.o:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/PMinterface.cpp.o
.PHONY : PMinterface.cpp.o

PMinterface.i: PMinterface.cpp.i
.PHONY : PMinterface.i

# target to preprocess a source file
PMinterface.cpp.i:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/PMinterface.cpp.i
.PHONY : PMinterface.cpp.i

PMinterface.s: PMinterface.cpp.s
.PHONY : PMinterface.s

# target to generate assembly for a file
PMinterface.cpp.s:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/PMinterface.cpp.s
.PHONY : PMinterface.cpp.s

PMmain.o: PMmain.cpp.o
.PHONY : PMmain.o

# target to build an object file
PMmain.cpp.o:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/PMmain.cpp.o
.PHONY : PMmain.cpp.o

PMmain.i: PMmain.cpp.i
.PHONY : PMmain.i

# target to preprocess a source file
PMmain.cpp.i:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/PMmain.cpp.i
.PHONY : PMmain.cpp.i

PMmain.s: PMmain.cpp.s
.PHONY : PMmain.s

# target to generate assembly for a file
PMmain.cpp.s:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/PMmain.cpp.s
.PHONY : PMmain.cpp.s

PMrepair.o: PMrepair.cpp.o
.PHONY : PMrepair.o

# target to build an object file
PMrepair.cpp.o:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/PMrepair.cpp.o
.PHONY : PMrepair.cpp.o

PMrepair.i: PMrepair.cpp.i
.PHONY : PMrepair.i

# target to preprocess a source file
PMrepair.cpp.i:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/PMrepair.cpp.i
.PHONY : PMrepair.cpp.i

PMrepair.s: PMrepair.cpp.s
.PHONY : PMrepair.s

# target to generate assembly for a file
PMrepair.cpp.s:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/PMrepair.cpp.s
.PHONY : PMrepair.cpp.s

PMshrink.o: PMshrink.cpp.o
.PHONY : PMshrink.o

# target to build an object file
PMshrink.cpp.o:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/PMshrink.cpp.o
.PHONY : PMshrink.cpp.o

PMshrink.i: PMshrink.cpp.i
.PHONY : PMshrink.i

# target to preprocess a source file
PMshrink.cpp.i:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/PMshrink.cpp.i
.PHONY : PMshrink.cpp.i

PMshrink.s: PMshrink.cpp.s
.PHONY : PMshrink.s

# target to generate assembly for a file
PMshrink.cpp.s:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/PMshrink.cpp.s
.PHONY : PMshrink.cpp.s

draw.o: draw.cpp.o
.PHONY : draw.o

# target to build an object file
draw.cpp.o:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/draw.cpp.o
.PHONY : draw.cpp.o

draw.i: draw.cpp.i
.PHONY : draw.i

# target to preprocess a source file
draw.cpp.i:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/draw.cpp.i
.PHONY : draw.cpp.i

draw.s: draw.cpp.s
.PHONY : draw.s

# target to generate assembly for a file
draw.cpp.s:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/draw.cpp.s
.PHONY : draw.cpp.s

graph.o: graph.cpp.o
.PHONY : graph.o

# target to build an object file
graph.cpp.o:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/graph.cpp.o
.PHONY : graph.cpp.o

graph.i: graph.cpp.i
.PHONY : graph.i

# target to preprocess a source file
graph.cpp.i:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/graph.cpp.i
.PHONY : graph.cpp.i

graph.s: graph.cpp.s
.PHONY : graph.s

# target to generate assembly for a file
graph.cpp.s:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/graph.cpp.s
.PHONY : graph.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/main.cpp.s
.PHONY : main.cpp.s

misc.o: misc.cpp.o
.PHONY : misc.o

# target to build an object file
misc.cpp.o:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/misc.cpp.o
.PHONY : misc.cpp.o

misc.i: misc.cpp.i
.PHONY : misc.i

# target to preprocess a source file
misc.cpp.i:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/misc.cpp.i
.PHONY : misc.cpp.i

misc.s: misc.cpp.s
.PHONY : misc.s

# target to generate assembly for a file
misc.cpp.s:
	$(MAKE) -f CMakeFiles/steiner.dir/build.make CMakeFiles/steiner.dir/misc.cpp.s
.PHONY : misc.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... steiner"
	@echo "... GEOM/GPMinit.o"
	@echo "... GEOM/GPMinit.i"
	@echo "... GEOM/GPMinit.s"
	@echo "... GEOM/GPMinterface.o"
	@echo "... GEOM/GPMinterface.i"
	@echo "... GEOM/GPMinterface.s"
	@echo "... GEOM/GPMkdtree.o"
	@echo "... GEOM/GPMkdtree.i"
	@echo "... GEOM/GPMkdtree.s"
	@echo "... GEOM/GPMmain.o"
	@echo "... GEOM/GPMmain.i"
	@echo "... GEOM/GPMmain.s"
	@echo "... MinCost/MinCost.o"
	@echo "... MinCost/MinCost.i"
	@echo "... MinCost/MinCost.s"
	@echo "... PMduals.o"
	@echo "... PMduals.i"
	@echo "... PMduals.s"
	@echo "... PMexpand.o"
	@echo "... PMexpand.i"
	@echo "... PMexpand.s"
	@echo "... PMinit.o"
	@echo "... PMinit.i"
	@echo "... PMinit.s"
	@echo "... PMinterface.o"
	@echo "... PMinterface.i"
	@echo "... PMinterface.s"
	@echo "... PMmain.o"
	@echo "... PMmain.i"
	@echo "... PMmain.s"
	@echo "... PMrepair.o"
	@echo "... PMrepair.i"
	@echo "... PMrepair.s"
	@echo "... PMshrink.o"
	@echo "... PMshrink.i"
	@echo "... PMshrink.s"
	@echo "... draw.o"
	@echo "... draw.i"
	@echo "... draw.s"
	@echo "... graph.o"
	@echo "... graph.i"
	@echo "... graph.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... misc.o"
	@echo "... misc.i"
	@echo "... misc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

